apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: test-cr
rules:
  - apiGroups:
      - ""
    resources:
      - secret
    verbs:
      - get
      - watch
      - create
      - list
      - patch
      - update
