apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: application
  namespace: argocd
  labels:
    istio-injection: enabled
    app.kubernetes.io/part-of: system-apps
  annotations:
    argocd.argoproj.io/sync-wave: "-80"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    path: ./charts/application
    repoURL: git@github.com:xzizka/argotest.git
    targetRevision: two-apps
#    helm:
#      valueFiles:
#        - ../values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true


