apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-role-binding-cluster-admin
  namespace: {{ .Values.namespace }}
subjects:
  - kind: ServiceAccount
    name: build-robot
    namespace: {{ .Values.namespace }}
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io