apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kube-system-role
  namespace: kube-system
subjects:
- kind: ServiceAccount
  name: build-robot
  namespace: {{ .Values.namespace }}
roleRef:
  kind: Role 
  name: kube-proxy
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kube-system-role
  namespace: {{ .Values.namespace }}
subjects:
- kind: ServiceAccount
  name: build-robot
  namespace: {{ .Values.namespace }}
roleRef:
  kind: Role 
  name: kube-proxy
  apiGroup: rbac.authorization.k8s.io