apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: {{ .Values.namespace }}
spec:
  containers:
  - image: nginx
    name: nginx
  serviceAccountName: build-robot
  automountServiceAccountToken: false
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: {{ .Values.namespace_diff }}
spec:
  containers:
  - image: nginx
    name: nginx
  serviceAccountName: build-robot
  automountServiceAccountToken: false