apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: test6
spec:
  containers:
  - image: nginx
    name: nginx
    securityContext:
      allowPrivilegeEscalation: true
  serviceAccountName: build-robot
  automountServiceAccountToken: true