apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: testrole
  namespace: {{ .Values.namespace }}
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "watch", "list"]
