apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: testrole
  namespace: {{ .Values.namespace }}
rules:
- apiGroups: [""]
  resources: ["pod"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: testrole
  namespace: test5
rules:
- apiGroups: [""]
  resources: ["pod"]
  verbs: ["get", "watch", "list"]