apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-pods
  namespace: {{ .Values.namespace }}
subjects:
- kind: ServiceAccount
  name: build-robot
  namespace: {{ .Values.namespace }}
roleRef:
  kind: Role 
  name: testrole 
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-pods
  namespace: {{ .Values.namespace_diff }}
subjects:
- kind: ServiceAccount
  name: build-robot
  namespace: {{ .Values.namespace_diff }}
roleRef:
  kind: Role 
  name: testrole 
  apiGroup: rbac.authorization.k8s.io