---
apiVersion: v1
kind: Secret
metadata:
  name: mysecret
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  username: YWRtaW4=
  password: MWYyZDFlMmU2N2Rm
---
apiVersion: v1
kind: Secret
metadata:
  name: mysecret
  namespace: test5
type: Opaque
data:
  username: YWRtaW4=
  password: MWYyZDFlMmU2N2Rm