apiVersion: v1
kind: ServiceAccount
metadata:
  name: build-robot
  namespace: {{ .Values.namespace }}
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: build-robot
  namespace: {{ .Values.namespace-diff }}
automountServiceAccountToken: false